version: '3'

services:
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:3.6.9-stretch
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: db
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: db
